console.log("Beginning");
prompt('What is your first name?');
var visitorName = prompt('What is your first and last name?');
alert(visitorName);
var message = "Hello!";
alert(message + ' ' + visitorName);
message = "Welcome to JavaScript Basics";
alert(message);
message = "He's a great JavaScript programmer!";
alert(message);
message = "<h1 class='special'>he\'s a special JavaScript programmer!</h1>";
alert(message);
message = "<h1 class=\'special\''>he's a very special JavaScript programmer!</h1>";
alert(message);
message = "he's a very special JavaScript programmer!";
var greeting = visitorName
greeting += ", " + message;
document.write(greeting);
document.write(greeting.length);
console.log(greeting.toUpperCase());
console.log(greeting);
var stringToShout = prompt('What should I shout?');
var shout = stringToShout.toUpperCase();
shout += "!!!";
alert(shout);
console.log('Ending');